### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "abhishek pratap",
  "email": "cia@gmail.com",
  "adress": "213 main street",
  "dateOfBirth": "1992-01-01",
  "registeredDate": "2024-12-11"
}

###